from .serializers import DeviceSerializer, TelemetrySerializer, AlertSerializer, DeviceLatestSerializer
from .models import Device, Telemetry, Alert
from rest_framework import viewsets
from rest_framework.mixins import CreateModelMixin
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.exceptions import ValidationError
from django.utils.dateparse import parse_datetime

# ViewSet for devices.Provides full CRUD (list, create, retrieve, update, delete).
# Custom actions: latest, telemetry
class DeviceViewSet(viewsets.ModelViewSet):
    serializer_class = DeviceSerializer
    queryset = Device.objects.all()

    #latest: returns the most recent telemetry for a device
    @action(detail=True, methods=["get"])
    def latest(self):
        device = self.get_object()
        telemetry = device.telemetries.select_related("device").order_by("-timestamp").first()
        if telemetry is None:
            return Response(status=404)
        else:
            return Response(DeviceLatestSerializer(telemetry).data)
        
    #telemetry: returns telemetry history filtered by ?from=&to= (paginated)
    @action(detail=True, methods=["get"])
    def telemetry(self):
        device = self.get_object()
        from_param = parse_datetime(self.request.query_params.get("from"))
        to_param = parse_datetime(self.request.query_params.get("to"))
        if from_param is None or to_param is None:
            raise ValidationError("'from' and 'to' are required")
        else:
            telemetry = device.telemetries.filter(timestamp__gte=from_param, timestamp__lte=to_param).order_by("-timestamp")
            page = self.paginate_queryset(telemetry)
            serializer = TelemetrySerializer(page, many=True)
            return self.get_paginated_response(serializer.data)

# ViewSet for telemetry ingestion.
# Only 'create' (POST) is enabled; other methods are disabled.
# Delegates validation and alert creation to TelemetrySerializer.      
class TelemetryViewSet(CreateModelMixin, viewsets.GenericViewSet):
    serializer_class = TelemetrySerializer
    queryset = Telemetry.objects.select_related("device").all()

# Read-only ViewSet for alerts.
# Alerts are generated by the server; clients can only list/retrieve them.
class AlertViewSet(viewsets.ReadOnlyModelViewSet):
    serializer_class = AlertSerializer
    queryset = Alert.objects.select_related("device").all()

